travis:
  secure:
    BINSTAR_TOKEN: hryYSVDaDqascKQU6gG0YIY4lTplx+o5kXpIzsI5wBf22Aydaj9iOuO3VUTQ9ieDCKDrRhq7qKQs75ZBB2bqnJw1vew09heXZCp0jwfCnNma14TgcJrWZ0jpUZSBGpxErcwEoi+MdCH1CB2vXnbysRM14sX2ASUt68yENSL+0PZ+be0cc8c+v5udTcL306E7HS9iG6CtSdAL8qjL8uGDNS3n5tq+AzYQdON9Imnh3No2GWro2VQVH3sit/3yYsQzNIdb6AS9buPnp62ljvDZZzXQBhp6f5Bmj6YyurVjc336GeRUhq6pO1HYXODOcm6IT4+D3tIsPPqc7fdZli7eY+7Jb6ZKrYdJHiAb87RnWsMD3F+VqJhP0Z1xFdcDJimDX+uRkrG/4D06H6oFVx4it7YQW7dxbeYFuYh791XVn0a5EHe2/tgNMxHL/dGQUenSbo02cTO1bJJCLxGsn39cQryD6hk3tqmWV6BjC4b1DRDlxqCDETsDuQkwLzS2ohBEdOnuJJ84orxAbn8Vny3rmCliKmWJqX/ASeWr6r6FudW750s+cwd1RNn72xBSh1vwzzDH5MVivGL1HmsUBwG1QHfAvre4UjDTcKsFdZWDbNLVaxlzi0m3TV/2ZP/nU+TB8JWBWsIBsY5uXTsAK9VYhiS2SpFIDNCUQc3eEGPuQ54=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
