travis:
  secure:
    BINSTAR_TOKEN: ycegGGLzWEVQOzW6B+BpkM+htIkwOBlUoCpsNzsQK1AaOut0yfI+DcKmKgcMBb+eG1WS9/fSlDAGXvAy5F+/F85zUhTXmEM1+Hm/c+T4RdeCQ4uz3sSr92Bk7eQ6sv/senCMVPNskDBvmRMfOVdqKcbyBGIuKqGxn7SEUjQNLhFo5kNtADCNpyNSk3lPC8qxrdVhFIfrBVJVnMC8dFSIhkaIMQ+AGDo/c8/0FB+qRtnTLTLQf8iVds6q9I2cgkaa0rOM5U1PwlE4KeOImBsYRU1ARaSMmdRhjiJPQVUKxNSurysKtfLlbVVRn93SojAo+AlMjApCIR0TVF5OdtwmQWHd1EXdyvp7vQ/l8eXEvY+YecLWd1Qwzk395bqj5rwd/3+zl2srqgCJXNlnGRCT55pL07KJfVN7pT2qW/V9tD++LWAxsML4AopyKSgq+bLvW4DBJtFoxnaknSHDwI/oxCErp41sgJBOdZzgG742omek21NwEgZlaPIRpx3R7JQrdz/Z8mqEuT84EUHlw+Wva71YXhQXMAaqy70mEfZ7pjiCEfhbOjdDG6PsZI1cphOr4dMY/PlvpfhhazVsh24F60kjdw/QxfGHWW1uZrWBfF0NLEOkGDdGwCmkZ3buyr5QyJxCr4nbeiq+l0YjXnvMqp9I7iWc42j5UTtqMfZNnyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
